#List of websites used in the program

WeedE1 = "https://www.dea.gov/factsheets/marijuana"
WeedE2 = "https://recovery.org/marijuana/history/"
WeedE3 = "https://nida.nih.gov/publications/research-reports/marijuana/what-are-marijuanas-long-term-effects-brain"
WeedP1 = "https://nida.nih.gov/publications/research-reports/marijuana/available-treatments-marijuana-use-disorders"
WeedP2 = "https://www.samhsa.gov/find-help/atod/marijuana-cbd"
WeedP3 = "https://link.springer.com/article/10.1023/A:1011173512033"
WeedL1 = "https://www.athenscriminallawyer.com/criminal-defense/drug-crimes/possession-of-marijuana/"
WeedL2 = "https://www.whitedeerrun.com/substance-abuse/marijuana/"
WeedL3 = "https://www.findlaw.com/state/pennsylvania-law/pennsylvania-marijuana-laws.html"

CocaineE1 = "https://www.dea.gov/factsheets/cocaine"
CocaineE2 = "https://recovery.org/cocaine/history/"
CocaineE3 = "https://nida.nih.gov/research-topics/cocaine"
CocaineP1 = "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6795516/"
CocaineP2 = "https://www.samhsa.gov/find-help/atod/other-drugs"
CocaineP3 = "https://psycnet.apa.org/doiLanding?doi=10.1037%2F0022-006X.68.3.515"
CocaineL1 = "https://www.athenscriminallawyer.com/criminal-defense/drug-crimes/possession-of-cocaine/"
CocaineL2 = "https://www.whitedeerrun.com/cocaine/"
CocaineL3 = "https://www.findlaw.com/state/pennsylvania-law/pennsylvania-cocaine-laws.html"

HeroinE1 = "https://www.dea.gov/factsheets/heroin"
HeroinE2 = "https://recovery.org/heroin/history/"
HeroinE3 = "https://nida.nih.gov/publications/research-reports/heroin/what-are-long-term-effects-heroin-use"
HeroinP1 = "https://nida.nih.gov/publications/research-reports/heroin/what-are-treatments-heroin-use-disorder"
HeroinP2 = "https://www.samhsa.gov/find-help/atod/other-drugs"
HeroinP3 = "https://www.lenus.ie/bitstream/handle/10147/45167/6859.pdf?sequence=1"
HeroinL1 = "https://www.athenscriminallawyer.com/criminal-defense/drug-crimes/possession-of-a-controlled-substance/"
HeroinL2 = "https://www.whitedeerrun.com/heroin/"
HeroinL3 = "https://www.findlaw.com/state/pennsylvania-law/pennsylvania-heroin-laws.html"

MethE1 = "https://www.dea.gov/factsheets/methamphetamine"
MethE2 = "https://recovery.org/methamphetamine/history/"
MethE3 = "https://nida.nih.gov/publications/research-reports/methamphetamine/what-are-long-term-effects-methamphetamine-misuse"
MethP1 = "https://nida.nih.gov/publications/research-reports/methamphetamine/what-treatments-are-effective-people-who-misuse-methamphetamine"
MethP2 = "https://www.samhsa.gov/find-help/atod/other-drugs"
MethP3 = "https://www.tandfonline.com/doi/abs/10.1080/14659891.2020.1800842"
MethL1 = "https://www.athenscriminallawyer.com/criminal-defense/drug-crimes/possession-of-methamphetamine/"
MethL2 = "https://www.whitedeerrun.com/substance-abuse/meth/"
MethL3 = "https://www.findlaw.com/state/pennsylvania-law/pennsylvania-drug-possession-laws.html#:~:text=In%20Pennsylvania%2C%20it%20is%20a,intentionally%20possessed%20a%20controlled%20substance."
